FROM resin/rpi-raspbian

RUN apt-get update
RUN apt-get -y install python python-zmq
COPY src /app

ENV ZMQ tcp://localhost:7777
ENV TOPIC dns
ENV GELF http://localhost:9500/gelf
ENV HOST dns_scan

CMD /usr/bin/python /app/dns_gelf.py --zmq ${ZMQ} --topic ${TOPIC} --gelf ${GELF} --host ${HOST}
